import base64
import subprocess
import sys

# Build the PowerShell script
lines = []
lines.append("$ErrorActionPreference = 'Continue'")
lines.append("$ProgressPreference = 'SilentlyContinue'")
lines.append("$cred = New-Object System.Management.Automation.PSCredential('GOLD-CLUB\\test', (ConvertTo-SecureString 'test' -AsPlainText -Force))")
lines.append("$computerName = '10.0.0.90'")
lines.append("$statePath = 'C:\\Goldclub\\var\\state\\goldclub.aurum.services\\GCMessenger\\SASControler1'")
lines.append("$historyPath = Join-Path $statePath 'History'")
lines.append("$logPath = 'C:\\Goldclub\\var\\log\\SlotLog\\2026-06-17.log'")
lines.append("Write-Host '=== Probe Hop 3: AFT XML State Manipulation ===' -ForegroundColor Cyan")
lines.append('Write-Host "Target: $computerName"')
lines.append("Write-Host ''")
lines.append("Write-Host '[1] Establishing WinRM session...' -ForegroundColor Yellow")
lines.append("try {")
lines.append("    $session = New-PSSession -ComputerName $computerName -Credential $cred -ErrorAction Stop")
lines.append("    Write-Host '    WinRM session established.' -ForegroundColor Green")
lines.append("} catch {")
lines.append('    Write-Host "    ERROR: $_" -ForegroundColor Red')
lines.append("    exit 1")
lines.append("}")
lines.append("")
lines.append("Write-Host ''")
lines.append("Write-Host '[2] Reading existing AFT state XML files...' -ForegroundColor Yellow")
lines.append("Invoke-Command -Session $session -ScriptBlock {")
lines.append("    param($statePath, $historyPath)")
lines.append("    $mostRecentPath = Join-Path $statePath 'GCC_ST_20664_01_aftMostRecentTransaction_v1.xml'")
lines.append("    if (Test-Path $mostRecentPath) {")
lines.append("        $xml = [xml](Get-Content $mostRecentPath -Raw)")
lines.append("        $txn = $xml.AftTransactionSerializer.aftTransaction")
lines.append("        $txnIdStr = ($txn.transactionId.char | ForEach-Object { [char][int]$_ }) -join ''")
lines.append("        $tsBytes = [System.Convert]::FromBase64String($txn.transactionCompletedDateTime)")
lines.append("        $hexStr = ($tsBytes | ForEach-Object { '{0:X2}' -f $_ }) -join ' '")
lines.append("        $expBytes = [System.Convert]::FromBase64String($txn.expiration.bcdData)")
lines.append("        $expHex = ($expBytes | ForEach-Object { '{0:X2}' -f $_ }) -join ' '")
lines.append('        Write-Host "    Version: $($xml.AftTransactionSerializer.version)"')
lines.append('        Write-Host "    Status: $($txn.transferStatus)"')
lines.append('        Write-Host "    Amount: $($txn.requestedNonRestrictedAmount)"')
lines.append('        Write-Host "    TxnId: $txnIdStr"')
lines.append('        Write-Host "    Timestamp bytes: $hexStr"')
lines.append('        Write-Host "    Expiration bytes: $expHex"')
lines.append('        Write-Host "    Cumulative: $($txn.comulativeNonRestrictedAmountMeter)"')
lines.append('        Write-Host "    Reported: $($txn.aftTransactionReported)"')
lines.append('        Write-Host "    Finished: $($txn.aftTransactionFinished)"')
lines.append('        Write-Host "    RequestMsg: $($txn.requestTextMessage)"')
lines.append("    }")
lines.append("    $settingsPath = Join-Path $statePath 'GCC_ST_20664_01_aftCurrentSettings_v2.xml'")
lines.append("    if (Test-Path $settingsPath) {")
lines.append("        $sxml = [xml](Get-Content $settingsPath -Raw)")
lines.append('        Write-Host "    Settings Ver: $($sxml.CurrentAftSettingsSerializer.version)"')
lines.append('        Write-Host "    RegStatus: $($sxml.CurrentAftSettingsSerializer.currentAftSettings.registrationStatus)"')
lines.append("    }")
lines.append("    $historyFiles = Get-ChildItem -Path $historyPath -Filter 'GCC_ST_20664_01_aftTransactionHistory_i*_v1.xml' | Sort-Object Name -Descending | Select-Object -First 1")
lines.append("    if ($historyFiles) {")
lines.append('        Write-Host "    Latest history: $($historyFiles.Name)"')
lines.append("        $hxml = [xml](Get-Content $historyFiles.FullName -Raw)")
lines.append("        $htxn = $hxml.AftTransactionCarrier.aftTransaction")
lines.append("        $hTxnIdStr = ($htxn.transactionId.char | ForEach-Object { [char][int]$_ }) -join ''")
lines.append('        Write-Host "    History TxnId: $hTxnIdStr Amount: $($htxn.requestedNonRestrictedAmount)"')
lines.append("    }")
lines.append("    $datFiles = Get-ChildItem -Path 'C:\\Goldclub\\var\\state\\goldclub.aurum.services' -Filter '*.dat' -Recurse -ErrorAction SilentlyContinue")
lines.append("    if ($datFiles) {")
lines.append('        Write-Host "    Found $($datFiles.Count) .dat files:"')
lines.append('        $datFiles | ForEach-Object { Write-Host "      $($_.FullName) $([math]::Round($_.Length/1024,1)) KB" }')
lines.append("    }")
lines.append("} -ArgumentList $statePath, $historyPath")

script = '\r\n'.join(lines)

# Write the script file
with open(r'c:\Users\Ezbogar\GoldclubLogInvestigator\Probe-AFT-XML-Spoof.ps1', 'wb') as f:
    f.write(script.encode('utf-8'))

print(f'Script written: {len(lines)} lines, {len(script)} chars')
